### ISSUE TITLE
Tight while loop, should add small delay (like 5ms or so)

### ISSUE THREAD

**Issue by bhavesh-k** [A223D/ArduinoESP32DataUpload#1]
https://github.com/A223D/ArduinoESP32DataUpload/blob/d93c680e55cf870548e66d75ab1b61318bebe240/dataUpload/dataUpload.ino#L105

**Comment by A223D** [comment]
Resolved in latest commit([284c408](https://github.com/A223D/ArduinoESP32DataUpload/commit/284c4084d49e13eed4ec0e31ccc4c6bbe3b242f6))
